log messages to file: C:\NatlinkGIT3\Natlink\PyTest\testresult.txt
starting unittestNatlink

starting tests with threading: 1

test recognitionMimicCommands, version: 15
testSampleMacros

--------------- errors -----------------

---------- testSampleMacros (__main__.UnittestNatlink) --------
Traceback (most recent call last):
  File "<string>", line 2337, in testSampleMacros
  File "<string>", line 1966, in doTestRecognition
natlink.MimicFailed: recognitionMimic call failed (The speech engine returned the following error: MimicNoResults)

--------------- failures -----------------

---------- testRecognitionMimicCommands (__main__.UnittestNatlink) --------
Traceback (most recent call last):
  File "<string>", line 1990, in doTestCommandRecognition
natlink.MimicFailed: recognitionMimic call failed (The speech engine returned the following error: MimicNoResults)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1191, in testRecognitionMimicCommands
  File "<string>", line 1995, in doTestCommandRecognition
AssertionError: ===test failed: MimicFailed, but expected 1 (words: ['mimic', 'two', 'bllackk'])
